name: table-py
version: 0.1.0
homepage: https://github.com/morloclib/table-py
synopsis: Python implementations for the table stdlib module
description: pyarrow-backed Table operations.
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/table-py
bug-reports: https://github.com/morloclib/table-py
